USE DB_InventariosGlobal;
GO

SELECT * FROM Inventario

ALTER DATABASE DB_InventariosGlobal
SET ALLOW_SNAPSHOT_ISOLATION ON

SET TRANSACTION ISOLATION LEVEL SNAPSHOT

BEGIN TRANSACTION invent

SELECT * FROM Inventario WHERE inventarioID = 281
WAITFOR DELAY '00:00:10'
SELECT * FROM Inventario WHERE inventarioID = 281

-- COMMIT TRANSACTION invent